### ISSUE TITLE
/etc/default/grub not properly modified

### ISSUE THREAD

**Issue by 0n0w1c** [zhanghua000/raspberrypi-uefi-boot#1]
Manjaro ARM

When /usr/share/libalpm/scripts/modify_grub_cmdline executes,
GRUB_CMDLINE_LINUX="" --> GRUB_CMDLINE_LINUX="${CMDLINE}"
Then no more modifications.

This works better for me:
PKGBUILD #232
```
- CMDLINE="\`sed 's/^root=.\+ rw //' \${CMDFILE}\`"
+ CMDLINE=`sed 's/^root=.\+ rw //' ${CMDFILE}`
```

PKGBUILD #233
```
- sed -i 's/^GRUB_CMDLINE_LINUX=""$/GRUB_CMDLINE_LINUX="\${CMDLINE}"/' /etc/default/grub
+ sed -i "s/^GRUB_CMDLINE_LINUX=.*/GRUB_CMDLINE_LINUX=\"${CMDLINE}\"/" /etc/default/grub
```

**Comment by zhanghua000** [comment]
I think this should help. I should't write `${CMDLINE}` or `${CMDFILE}` directly as these should be variable names in `/usr/share/libalpm/scripts/modify_grub_cmdline`. If I do so, there will be static values in script rather than proper variable names. In file `PKGBUILD` lines 225-239, I am creating script which should be executed by pacman hook.

**Comment by 0n0w1c** [comment]
PKGBUILD #233
```
- if [[ \${CMDLINE} != "" ]]
+ if [[ \${CMDLINE} != "" ]];then
```

**Comment by 0n0w1c** [comment]
PKGBUILD #234
```
sed -i "s/^GRUB_CMDLINE_LINUX=\"\"$/GRUB_CMDLINE_LINUX=\"\${CMDLINE}\"/" /etc/default/grub
```
Only updates when `=""`

Maybe `="` is better?
```
sed -i "s/^GRUB_CMDLINE_LINUX=\"$/GRUB_CMDLINE_LINUX=\"\${CMDLINE}\"/" /etc/default/grub
```

Then modify_grub_cmdline will update when executed. Not only when exact match of `=""`.
I assume this is your design goal, since you coded the hook to execute when cmdline.txt is modified.
But maybe you intend updates only when reset to `=""`?

**Comment by zhanghua000** [comment]
> PKGBUILD #233
> 
> ```
> - if [[ \${CMDLINE} != "" ]]
> + if [[ \${CMDLINE} != "" ]];then
> ```

Ah sorry I forget to check this, I will fix this now.

> PKGBUILD #234
> 
> ```
> sed -i "s/^GRUB_CMDLINE_LINUX=\"\"$/GRUB_CMDLINE_LINUX=\"\${CMDLINE}\"/" /etc/default/grub
> ```
> 
> Only updates when `=""`
> 
> Maybe `="` is better?
> 
> ```
> sed -i "s/^GRUB_CMDLINE_LINUX=\"$/GRUB_CMDLINE_LINUX=\"\${CMDLINE}\"/" /etc/default/grub
> ```
> 
> Then modify_grub_cmdline will update when executed. Not only when exact match of `=""`.
> I assume this is your design goal, since you coded the hook to execute when cmdline.txt is modified.
> But maybe you intend updates only when reset to `=""`?


My goal is that only when `/etc/default/grub` is not modified and one of  `/boot/cmdline.txt{,.pacsave}` exists and has proper content will we modify `GRUB_CMDLINE_LINUX`. In default, `GRUB_CMDLINE_LINUX=""` is in `/etc/default/grub`'s content. If you had modified `/etc/default/grub` before, I think you should manully merge changes so I let the script do nothing.

**Comment by 0n0w1c** [comment]
Ah, very well, I understand now. Thank you.

**Comment by zhanghua000** [comment]
I will close this issue now. If you find any other problem, feel free to reopen it.
